routes/web.php
<?php


use App\Http\Controllers\ClientController;

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\HomeController;

use App\Http\Controllers\ImageController;
use App\Http\Controllers\MailController;

use App\Http\Controllers\ThemeController;
use App\Models\Mail;
use Asseco\Inbox\Contracts\CanMatch;
use Asseco\Inbox\Inbox;
use BeyondCode\Mailbox\Facades\Mailbox;
use BeyondCode\Mailbox\InboundEmail;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('login');
});

Route::group(['prefix' => LaravelLocalization::setLocale()], function () {
    Route::get('/', [HomeController::class, 'index'])->name("home");
    Route::get('/request-service', [HomeController::class, 'request'])->name("request-service");

});


Route::middleware(['auth:sanctum', 'verified'])->prefix(LaravelLocalization::setLocale() . '/admin')->group(function () {


    Route::get('dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('change-theme/{color}', ThemeController::class)->name('change.theme');
    Route::get('images/index', [ImageController::class, 'index'])->name('image.index');
    Route::post('images/update', [ImageController::class, 'update'])->name('image.update');
    Route::prefix('clients')->name('clients.')->group(function () {
        Route::get('data-tables', [ClientController::class, 'datatables'])->name('datatables');
        Route::put('/{id}/main-details/update', [ClientController::class, 'updateClientDetails'])->name('main-details.update');
    });
    //


    Route::get('all/data-tables', [MailController::class, 'datatables'])->name('mails.datatables');
    Route::post('mails/send_message', [MailController::class, 'send'])->name('mails.send');
    Route::get('all-meals', [MailController::class, 'mails'])->name('mails.index');
    Route::put('setting/mails', [MailController::class, 'settingUpdate'])->name('setting.mail.update');
    Route::get('setting/mails/{type}', [MailController::class, 'setting'])->name('setting.mail');
    Route::get('mail/new', [MailController::class, 'create'])->name('mails.create');





});





/*Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');*/
Route::get("data", function () {
    $client = Webklex\IMAP\Facades\Client::account('default');

//Connect to the IMAP Server
    $client->connect();

//Get all Mailboxes

    $folders = $client->getFolders();
    $folders = $client->getFolder('All Mail');

    //Get all Messages of the current Mailbox $folder
    /** @var \Webklex\PHPIMAP\Support\MessageCollection $messages */
    $messages = $folders->messages()->all()->limit($limit = 10, $page = 1)->get();


});

app/Models/Client.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Client
 *
 * @property int $id
 * @property string $first_name
 * @property string $family_name
 * @property string $mobile
 * @property string $email
 * @property int $age
 * @mixin \Eloquent
 * @property string $status
 */
class Client extends BaseModel
{
    use HasFactory;

    protected $fillable = ['first_name' ,'family_name' ,'mobile' , 'email' , 'age'];




    public function  client_details(){
        return $this->hasOne(ClientDetails::class);
    }

}

app/Http/Controllers/ClientController.php
<?php


namespace App\Http\Controllers;


use App\Http\Controllers\Base\AdminController;
use App\Models\Client;
use App\Models\ClientDetails;
use App\Models\RequestService;
use App\Support\Icons;
use Illuminate\Http\Request;

class ClientController extends AdminController
{


    public function datatables(Request $request)
    {
        $clients = Client::all();
        return datatables()->of($clients)
            ->addColumn('date', function (Client $client) {
                return $client->created_at->todatestring();
            })->addColumn('status', function (Client $client) {
                return __($client->status);
            })->addColumn('action', function (Client $client) {
                $html = '<a href="' . route('clients.edit', $client->id) . '" class="btn btn-sm btn-clean btn-icon mr-2">' . Icons::EditIcon() . '</a>';
                $html .= '<a href="' . route('clients.show', $client->id) . '" class="btn btn-sm btn-clean btn-icon mr-2">' . Icons::ShowIcon() . '</a>';
                return $html;
            })->rawColumns(['action'])
            ->make(true);

    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $columns = [

            'first_name',
            'family_name',
            'email',
            'mobile',
            'age',
            'date',
            'status'
        ];
        return view('admin.pages.client.index')->with(['columns' => $columns]);
    }

    public function edit($id)
    {
        $client = Client::find($id);

        return view('admin.pages.client.edit')->with([
            'client' => $client,
        ]);
    }


    public function show($id)
    {

        $client = Client::find($id);

        return view('admin.pages.client.show')->with(['client' => $client]);

    }


    public function updateClientDetails($id, Request $request)
    {
        $client = Client::find($id);

        if (!$client) {
            session()->flash('error', __('The Data is Invalid'));
            return back();

        }
        $client_details = $client->client_details;

        if (!$client_details) {
            $client_details = new ClientDetails;
            $client_details->client_id = $id ;
        }


        try {
            $client_details->fill($request->only('address', 'city', 'zip_code',
                'country', 'street','house_number', 'born_place', 'birthday'
            ));

            $res = $client_details->save();
            if ($res) {
                session()->flash('success', __('Update Main Client Details'));
            }
        } catch (\Exception $e){
            session()->flash('error', __($e->getMessage()));
        }

        return back();
    }
}

resources/views/admin/pages/client/edit.blade.php
@extends('admin.layouts.app')
@section('content')
    <form id="create" action="{{route('clients.update',$client->id)}}" method="post" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <x-card-content>
            <x-card-header>
                <x-card-title>
                    {{ __('Edit Client')}}
                </x-card-title>
                <x-card-toolbar>
                    <x-back-btn :route="route('clients.index')"/>
                </x-card-toolbar>
            </x-card-header>
            <x-card-body>

                <div class="row">
                    <x-input-field :title="__('First Name')" name="first_name" type="text" required col="4"
                                   :model="$client"/>
                    <x-input-field :title="__('Family Name')" name="family_name" type="text" required col="4"
                                   :model="$client"/>
                    <x-input-field :title="__('Mobile')" name="mobile" type="text" required col="4"
                                   :model="$client"/>
                    <x-input-field :title="__('Email')" name="email" type="text" required col="4"
                                   :model="$client"/>

                    <x-input-field :title="__('Age')" name="age" type="text" required col="4" :model="$client"/>

                </div>
            </x-card-body>
            <x-card-footer>
                <x-buttons.update-button/>
            </x-card-footer>
        </x-card-content>
    </form>
@stop

resources/views/admin/pages/client/index.blade.php
@extends('admin.layouts.app')

@section('content')
    <x-card-content>
        <x-card-header>
            <x-card-title>
                {{__('Clients')}}
            </x-card-title>
            <x-card-toolbar>

            </x-card-toolbar>
        </x-card-header>
        <x-card-body>
            <x-datatable.html-structure>
                <th>{{__('First Name')}}</th>
                <th>{{__('Last Name')}}</th>
                <th>{{__('Email')}}</th>
                <th>{{__('Phone')}}</th>
                <th>{{__('Age')}}</th>
                <th>{{__('Created at')}}</th>
                <th>{{__('status')}}</th>

            </x-datatable.html-structure>
        </x-card-body>
    </x-card-content>
    <x-model.delete-model-confirmation/>
@endsection

@section('scripts')
    <x-datatable.script
        :columns="$columns"
        :route="route('clients.datatables')"
        :enableId="true"
    />
@endsection